/**
 * @file thermal_page.h
 * @brief Embedded HTML page for thermal camera live view
 *
 * This HTML page auto-refreshes the thermal BMP image from the EKH05
 * HTTP server. Access via: http://<device-ip>/thermal.html
 *
 * Add this to the lwIP httpd fsdata alongside the existing EKH05 Demo pages.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef THERMAL_PAGE_H
#define THERMAL_PAGE_H

static const char thermal_html_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<title>EKH05 Thermal Camera - Lepton 3.5</title>\n"
"<style>\n"
"  body { background: #1a1a2e; color: #eee; font-family: monospace;\n"
"         display: flex; flex-direction: column; align-items: center;\n"
"         margin: 0; padding: 20px; }\n"
"  h1 { color: #ff6b35; margin-bottom: 5px; }\n"
"  .subtitle { color: #888; font-size: 12px; margin-bottom: 15px; }\n"
"  .container { display: flex; gap: 20px; flex-wrap: wrap;\n"
"               justify-content: center; }\n"
"  .panel { background: #16213e; border: 1px solid #0f3460;\n"
"           border-radius: 8px; padding: 15px; }\n"
"  #thermal-img { width: 480px; height: 360px;\n"
"                 image-rendering: pixelated;\n"
"                 border: 2px solid #ff6b35; border-radius: 4px; }\n"
"  .stats { display: grid; grid-template-columns: 1fr 1fr;\n"
"           gap: 8px; min-width: 200px; }\n"
"  .stat-item { background: #0f3460; padding: 8px;\n"
"               border-radius: 4px; text-align: center; }\n"
"  .stat-label { color: #888; font-size: 11px; }\n"
"  .stat-value { color: #e94560; font-size: 18px; font-weight: bold; }\n"
"  .controls { margin-top: 10px; }\n"
"  button { background: #e94560; color: white; border: none;\n"
"           padding: 8px 16px; border-radius: 4px; cursor: pointer;\n"
"           font-family: monospace; font-size: 13px; margin: 3px; }\n"
"  button:hover { background: #ff6b35; }\n"
"  button:disabled { background: #555; cursor: not-allowed; }\n"
"  .status { color: #4ecca3; font-size: 12px; margin-top: 8px; }\n"
"  .colorbar { width: 480px; height: 20px; border-radius: 4px;\n"
"              background: linear-gradient(to right,\n"
"                #000000, #00004f, #5a0080, #8f0000, #e13000,\n"
"                #f07d00, #f8c800, #ffffa0, #ffffff);\n"
"              margin-top: 5px; }\n"
"  .colorbar-labels { width: 480px; display: flex;\n"
"                     justify-content: space-between;\n"
"                     font-size: 10px; color: #888; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"  <h1>FLIR Lepton 3.5 Thermal View</h1>\n"
"  <div class=\"subtitle\">MM6108-EKH05 | Wi-Fi HaLow | 160x120</div>\n"
"\n"
"  <div class=\"container\">\n"
"    <div class=\"panel\">\n"
"      <img id=\"thermal-img\" src=\"/thermal.bmp\" alt=\"Thermal\">\n"
"      <div class=\"colorbar\"></div>\n"
"      <div class=\"colorbar-labels\">\n"
"        <span>Cold</span><span>Hot</span>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div class=\"panel\">\n"
"      <h3 style=\"margin-top:0;color:#4ecca3\">Sensor Stats</h3>\n"
"      <div class=\"stats\">\n"
"        <div class=\"stat-item\">\n"
"          <div class=\"stat-label\">MIN</div>\n"
"          <div class=\"stat-value\" id=\"s-min\">--</div>\n"
"        </div>\n"
"        <div class=\"stat-item\">\n"
"          <div class=\"stat-label\">MAX</div>\n"
"          <div class=\"stat-value\" id=\"s-max\">--</div>\n"
"        </div>\n"
"        <div class=\"stat-item\">\n"
"          <div class=\"stat-label\">MEAN</div>\n"
"          <div class=\"stat-value\" id=\"s-mean\">--</div>\n"
"        </div>\n"
"        <div class=\"stat-item\">\n"
"          <div class=\"stat-label\">FRAMES</div>\n"
"          <div class=\"stat-value\" id=\"s-frames\">0</div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <div class=\"controls\">\n"
"        <button onclick=\"doFFC()\">FFC Calibrate</button>\n"
"        <button onclick=\"toggleStream()\" id=\"btn-stream\">Pause</button>\n"
"      </div>\n"
"\n"
"      <div class=\"status\" id=\"status\">Connecting...</div>\n"
"    </div>\n"
"  </div>\n"
"\n"
"<script>\n"
"var streaming = true;\n"
"var img = document.getElementById('thermal-img');\n"
"var interval;\n"
"\n"
"function refreshImage() {\n"
"  if (!streaming) return;\n"
"  img.src = '/thermal.bmp?t=' + Date.now();\n"
"}\n"
"\n"
"function updateStats() {\n"
"  fetch('/thermal.json')\n"
"    .then(r => r.json())\n"
"    .then(d => {\n"
"      document.getElementById('s-min').textContent = d.min;\n"
"      document.getElementById('s-max').textContent = d.max;\n"
"      document.getElementById('s-mean').textContent = d.mean;\n"
"      document.getElementById('s-frames').textContent = d.frames;\n"
"      document.getElementById('status').textContent =\n"
"        d.running ? 'Streaming @ ~8 fps' : 'Camera offline';\n"
"    })\n"
"    .catch(() => {\n"
"      document.getElementById('status').textContent = 'Connection lost';\n"
"    });\n"
"}\n"
"\n"
"function doFFC() {\n"
"  document.getElementById('status').textContent = 'Calibrating...';\n"
"  fetch('/thermal_ffc')\n"
"    .then(r => r.json())\n"
"    .then(d => {\n"
"      document.getElementById('status').textContent = d.message;\n"
"    });\n"
"}\n"
"\n"
"function toggleStream() {\n"
"  streaming = !streaming;\n"
"  document.getElementById('btn-stream').textContent =\n"
"    streaming ? 'Pause' : 'Resume';\n"
"}\n"
"\n"
"/* Refresh image every 200ms (~5fps in browser) */\n"
"img.onload = function() { setTimeout(refreshImage, 200); };\n"
"img.onerror = function() { setTimeout(refreshImage, 1000); };\n"
"refreshImage();\n"
"\n"
"/* Update stats every 2 seconds */\n"
"setInterval(updateStats, 2000);\n"
"updateStats();\n"
"</script>\n"
"</body>\n"
"</html>\n";

static const uint32_t thermal_html_page_len = sizeof(thermal_html_page) - 1;

#endif /* THERMAL_PAGE_H */
